# Edit - No sudo
dependencies:
  build:
    - anaconda3:latest

build_targets:
  - name: default
    environment:
      - CXXFLAGS=-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security
    commands:
      - apt-get -y update
      - apt-get -y install autoconf build-essential libopenmpi-dev g++
      # mpi4py seems to be here, also the anaconda channel?
      - conda config --add channels intel
      - conda install python=3.6 numpy scipy mpi4py swig
      # to avoid interference with MPI
      #- test -n $CC  && unset CC:
      #- test -n $CXX && unset CXX
      - ./bootstrap
      #- ./externals/autotools/bin/autoreconf -f -i
      - autoreconf -f -i
      - python ./preconfigure.py --prefix=/workspace/build --enable-PY_WRAPPER --disable-tecio
      - make -j 4
      - make install

ci:
  builds:
    - name: build
      build_target: default

# another edit
