# Edit - No sudo
dependencies:
  build:
    - python:3.6.0

build_targets:
  - name: default
    environment:
      - CXXFLAGS="-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security" 
      - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER --disable-tecio"
    commands:
      - apt-get update -qq
      - apt-get install -qq build-essential libopenmpi-dev
      - pip install numpy scipy mpi4py
      - ./bootstrap
      - autoreconf -f -i
      - ./preconfigure.py --prefix=/workspace/build --enable-PY_WRAPPER --disable-tecio
      - make -j 4
      - make install
ci:
  builds:
    - name: build
      build_target: default

# another edit
